name: "Victron GX MQTT Discovery"
description: "Home Assistant auto-discovery for Victron equipment"
url: "https://github.com/mnigbur/hass-victron-mqtt-discovery"
version: "0.1.7-r2"
slug: "hass-victron-mqtt-discovery"
init: false
arch:
  - aarch64
  - amd64
startup: application
hassio_api: true
services:
  - mqtt:want
options:
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  asset_modbus_registers_url: "https://www.victronenergy.com/upload/documents/CCGX-Modbus-TCP-register-list-3.50.xlsx"
  asset_sensor_documentation_url: "https://developers.home-assistant.io/docs/core/entity/sensor/"
schema:
  mqtt_host: str?
  mqtt_port: int
  mqtt_username: str?
  mqtt_password: str?
  asset_modbus_registers_url: str
  asset_sensor_documentation_url: str